<template>
  <v-container>
    <v-row class="d-flex align-start">
      <v-col lg="9" class="my-5 pr-5">
        <h1 class="indigo--text text--lighten-1 text-center">
          {{ dia.titulo }}
        </h1>
        <p class="mb-5 text-center" v-html="dia.subtitulo"></p>
        <ol class="pt-3">
          <li class="text-justify mt-3" v-for="(item, i) in dia.texto" :key="i">
            <p>{{ dia.texto[i] }}</p>
          </li>
        </ol>
      </v-col>
      <v-col lg="3" class="pl-2"><PanelDerecho /></v-col>
    </v-row>
  </v-container>
</template>
<script>
import PanelDerecho from "../components/Inicio/PanelDerecho";
export default {
  name: "MeditacionesDiarias",
  components: {
    PanelDerecho,
  },
  data() {
    return {
      Lunes: {
        titulo: "LUNES",
        subtitulo:
          "Segundo Rayo Dorado de la Sabiduría, la Iluminación, el Amor y la Paz.",
        texto: ['Mi Amado Ser Crístico, “YO SOY” en mí: ¿Te amo, te adoro! Invoco la Llama Dorada de la Iluminación y el Amor del Cristo Cósmico, para que me envuelva en este día. “YO SOY” la Iluminación y la Sabiduría dirigiéndome en todo lo que hago. Escucho, comprendo y bendigo todo lo que contacte hoy.',
        'Ahora realizo que viva, dentro de mi cuerpo físico, está la Llama de la Curación que me sana de toda imperfección. Ahora realizo que vivo, dentro de mi cuerpo físico, está el infinito Poder Proveedor de todas mis necesidades y requerimientos. Ahora realizo que viva, dentro de mi cuerpo físico está, la Iluminación de mi conciencia exterior. Ahora realizo que viva, dentro de mi cuerpo físico, está la Inteligencia mediante la cual todas las formas me darán la perfección que existe dentro de su esencia primaria. Ahora realizo que sólo existe un único poder: Dios dentro de mi corazón, y que ese poder actúa para mí según la Fe que tenga en Él. Por lo tanto, mi Santo Ser Crístico,”YO SOY” en mí, te invoco para que cumplas tu Plan Divino.',
        'El Amado Maestro KOOT HOOMI, Cristo de la Tierra, dice: “Amado corazón: No hagas grandes esfuerzos para ir a encontrar la Presencia de Dios. Aquiétate y encuéntrala en la paz de tu mundo sensorio. Abre los ojos y realiza el Majestuoso Poder de Dios que se encuentra en el latido de tu corazón, y permite que esa Naturaleza Divina sea testigo de la convicción acerca de la Omnipotencia y el Amor de la Presencia de Dios, que enciende tu propio mundo. ¿Quieres hacer una cosa? Cada mañana, mientras medites sobre la naturaleza de tu Presencia, el Poder de tu Presencia, la Maestría de tu Presencia, después de contemplarla por un momento, haz un pequeño esfuerzo adicional y trata de ser esa PRESENCIA sólo por media hora. Esto es lo que le pido a aquellas corrientes de vida que desean servirnos; pero mantente alerta ante el pequeño gusanillo del orgullo espiritual que a menudo, en el propio centro de tu bella flor espiritual, desea destruir su perfección.',
        'Amado Maestro KOOT HOOMI: Te amo, te bendigo y te doy gracias por tu gran servicio a mi y a toda la humanidad. Haz que Tu Sabiduría, Tu Paz y Tu Corazón Comprensivo me envuelvan para que siempre pueda comprender a mi hermano humano y darle la ayuda que más necesite.',
        'La Amada Lady SOO SHEE, Chohán de Segundo Rayo, dice: “Cada corriente de vida individual vino a la Tierra con un hermoso Loto, para nutrirlo y traerlo a la plena manifestación como una gloriosa Flor. Vida tras vida, dicha corriente de vida se ha dedicado a arrancar un pétalo tras otro, al igual que hemos visto hacer a muchos niños, diciendo: “Me ama…no me ama”. Eso es lo que ha ocurrido con las corrientes de vida, a través de los siglos. Al final de cada encarnación, sólo quedaba un tallo desnudo, el propio centro corazón sosteniendo quizás uno o dos pétalos. Y luego, cuando estaban del “otro lado de la vida”, al ver lo que le habían hecho a la flor, se comprometían con toda determinación a venir otra vez y nutrir el Loto. Ahora, por favor, separen su conciencia de la humano y visualícense a sí mismos entrando al gran Loto de Nuestro Retiro. Vean al Amado Maestro Confucio atraerlos bondadosamente hacia los pétalos sagrados del Loto Dorado de la Sabiduría. Permitan que esa Esencia Sagrada se infiltre en sus conciencias. No piensen en sus vehículos inferiores. Sólo dejen que fluya ese Elixir a través de sus conciencias y que la Luz Dorada llene su Ser, de tal manera que más tarde puedan decir: ¡Gracias a Dios que escuché!”',
        'Amada SOO SHEE: Te amo, te bendigo y te doy las gracias por Tu gran servicio a mí y a toda la humanidad. Que la Gran Llama de la Iluminación y la Sabiduría, desde Tu retiro del Loto Dorado, se expanda a través del Loto de nuestro seres para bendecir y ascender a toda la humanidad.',
        'El Amado Maestro Ascendido LANTO, Instructor Mundial y Patriarca del Retiro de las Montañas Rocallosas, dice: “En vuestro nuevo servicio, a menudo sienten la ingratitud e indiferencia de la humanidad y a veces se cansan de hacer el bien. Con frecuencia, cuando estamos en vuestra atmósfera, observamos el desaliento que los invade. Recuerden, por favor, a aquellos de nosotros que hemos pasado millones de años en idéntico servicio; millones de años amándolos, bendiciéndolos y poniendo nuestra Fe y confianza en ustedes. Al realizar esto, gozarán retornando y retribuyendo con la misma paciencia, confianza y fe a vuestros hermanos humanos”.',
        'Amado Maestro LANTO: Te amo, te bendigo y te doy gracias por tu servicio a nuestra Tierra durante tantos siglos. Ayúdanos a sentir esa gran reverencia por toda vida que tú tienes, y el amor que ayuda a liberarla.',
        'El Amado CONFUCIO, Anfitrión del Retiro de las Montañas Rocallosas y Director del Segundo Rayo, dice: “Toda Edad Dorada comienza con el embrión de Uno o Dos Seres. Ustedes tienen el Foco de la Llama Violeta, la Presencia del Maestro Ascendido Saint Germain y de su Representante en la Tierra. Este embrión, compuesto de Seres individuales, es inteligente porque dentro de su corazón se encuentra el Rayo Cósmico del Maestro Ascendido Saint Germain. ¿Eres tú parte de ese embrión? Para poder precipitar la Edad Dorada tú debes tener el Poder cohesivo del Amor Divino. Al protegerse el embrión y al afinarse las células que forman el Centro del Corazón, el cuerpo espiritual crece”.',
        'Amado CONFUCIO: Te damos las gracias por tus palabras de Amor. ¡Dótanos con tu Poder del Silencio para ayudar a manifestar en Paz el Plan Divino para la Edad Dorada!',
        'El Amado JOFIEL, Arcángel de la Iluminación, dice: “Mi servicio a la vida es educar la conciencia, capacitándola para descubrir DENTRO DE SÍ MISMA eso que es el PODER DE LA LUZ. En la Segunda Esfera, las ideas llegan a cristalizarse, toman forma. Si recibes una idea abstracta para construir un nuevo hogar, tu mente te puede decir: “Me gustaría un hogar con ocho habitaciones, con un acre de terreno”. Si la idea te agrada, tus sentimientos se precipitan hacia ella, energizan la forma, la presión de tus sentimientos le da vida y la traes a la manifestación”.',
        'Amado JOFIEL: Te amo, te bendigo y te doy gracias por tus servicios a toda la humanidad. Cárgame con tu sentimiento del Poder de Dios dentro de mi propio corazón para poder dominar todas las circunstancias que enfrente, con el Poder del Amor y la Luz exteriorizados, y enséñame a manifestar las ideas que me vienen de Dios.',
        'El Amado CASIOPEA, Elohim de la Sabiduría, dice: “El propósito del Segundo Rayo es la percepción activa y la contemplación iluminada del Plan y Diseño de Dios. Después que hayas tomado la decisión de cumplir la Voluntad de Dios, recibirás las Ideas Divinas y la instrucción acerca de cómo manifestarla. Por consiguiente, la primera actividad del cuerpo mental, después de tomar la decisión de actuar, es AQUIETARSE. Dentro de tu corazón está la Llama Dorada de la Iluminación que te revelará la Verdad”.',
        'Amado CASIOPEA: Te amo, te adoro y te doy las gracias por todo lo que significas para nuestra Tierra y toda la humanidad. Ayúdame a persistir en esta ciencia de la “Precipitación” y a manifestar cada día una idea recibida del Padre, para exteriorizarla concientemente. Gracias.'],
      },
      Martes: {
        titulo: "MARTES",
        subtitulo: "Tercer Rayo Rosa del Amor Divino y la Adoración.",
        texto: ['Amada Presencia de Dios, “YO SOY” en mí: ¡Te amo, te adoro! ¡Oh Magna y Poderosa Llama dentro de mi corazón! Envío mi amor y adoración continua a Ti, al Gran Dios del Universo y a sus Mensajeros. Envío mi amor a la vida en todas partes. Bendigo toda vida que yo contacte este día en pensamientos, sentimientos, palabras o acciones. No critico, no condeno, ni juzgo en este día. No quiero que nada de mi vida salga de mí sin encarnar una bendición. “YO SOY” sellado en la Llama Rosa del Amor Divino. “YO SOY” una Presencia confortadora para toda vida en todas partes.',
        'El Amado PABLO EL VENECIANO, anterior Director del Tercer Rayo y actual Mahá Chohán, dice: “Ven conmigo hoy, apartándote de todas las angustias del ser exterior. Entra a tu corazón, a la ´morada secreta del Altísimo`, y mientras estás allí contemplando la Llama Triple, que es la vestidura de tu bello Ser Crístico, relájate en el Amor y la Presencia de Dios. A medida que tu Adoración fluye hacia esa Presencia, recuerda que tu cuerpo es el templo donde mora la Llama Inmortal de la vida eterna, en la cual está el Ser Crístico –hecho a imagen y semejanza de Dios- esperando tu amor, tu adoración y tu devoción. A aquellos que rara vez le piden asistencia, les dice: “Yo puedo ser todo eso que me pides, amado, todo eso y mucho más`. Cuando la adoración sea una actividad constante dentro de ti, este Ser Crístico crecerá, se expandirá. No necesitarás palabras para proclamarlo. La luz siempre creciente que irradiará su Presencia, la cual responderá a la vida que derramas en Él, se hará visible como un aura radiante a tu alrededor; y todos la verán”.',
        'Amado PABLO EL VENECIANO: Te amo, te adoro, te doy gracias por lo que has hecho por mí y por toda la humanidad. Enséñame a ser una persona suave, dotada con Tus Dones de Tolerancia, Diplomacia, Comprensión y Habilidad para congeniar con mis compañeros humanos.',
        'La Amada Maestra LADY ROWENA, Chohán del Tercer Rayo, dice: “Estar centrado en la Inmortal Llama Triple dentro del corazón le asegura al individuo la libertad de todo lo que sea menor a la Perfección Crística. Por eso es tan importante que los discípulos que están bajo nuestra dirección practiquen diariamente este ejercicio, ya que cuanto más usen una actividad, más eficaz se vuelve el individuo. La meta de todos aquellos que están bajo la supervisión personal de los Seres Cósmicos y de los Maestros de la Sabiduría es y debe ser alcanzar la talla espiritual del Cristo en acción, en todo momento, permitiéndole así a ese Ser Glorioso dirigir inteligentemente todas sus acciones. Es de la mayor importancia que los discípulos se apropien de las bendiciones y la radiación del Tercer Rayo, por medio de la contemplación del Amor Divino y del Equilibrio que el mismo contiene. Llegar a convertirse en un ´Cristo en acción en el mundo de la forma` es prestar una ayuda inteligente, es colaborar con los Consejeros Espirituales, es seguir la dirección del Ser Crístico para traer iluminación a la conciencia exterior, y es ser un centro irradiador de Puro Amor Divino para las evoluciones de la Tierra. ¡Ay, Amados! Yo les aseguro que una vez que han experimentado realmente la forma de vivir del Cristo, todo lo demás se esfuma en la insignificancia y ustedes se vuelven Uno con Nosotros, que somos Uno con la Vida y sus manifestaciones. Recuerden siempre que armonizarse con la Unidad del Todo es estar identificado con la Perfección que existe en toda manifestación, es comprobar que todo contiene dentro de sí el Principio Activo del Dios Padre-Madre”.',
        'Amada LADY ROWENA: Te amo, te bendigo y te doy gracias por todo lo que significas para toda la humanidad, en todas partes. Ayúdame a mantener mi atención centrada en el Ser Crístico que está anclado dentro de mi corazón, para que yo pueda exteriorizar su Gran Perfección en todo lo que haga, piense, diga o sienta, en toda las actividades de mi mundo y mis asuntos.',
        'El Amado ARCÁNGEL CHAMUEL, Arcángel de la Adoración, dice: “La Llama de la Adoración es una de las actividades más prácticas que se pueda generar dentro del corazón, alma y espíritu de aquellos que están atados, ya que es un tratamiento para la mente, los sentimientos, y una verdadera terapia para la carne. La verdadera adoración a Dios no contiene búsqueda personal. Es una absoluta relajación; es reposar, asoleándose en la bondad de Dios, amándolo por Él mismo, o amando a cualquiera de los seres divinos que representan algún servicio especial a la vida. Yo reto a cualquier individuo que esté deprimido, a cualquiera que se encuentre dolorido, a cualquiera que se sienta encadenado de cualquier manera, a que utilice la Llama de la Adoración –que es la verdadera naturaleza del Ser- y si al usarla no sienten o ven la liberación, entonces el sol y los planetas no seguirán moviéndose en sus respectivas órbitas”.',
        'Amado CHAMUEL: Te amo, te doy gracias por tu bendita asistencia a mí y a toda la humanidad. Enciende y flamea tu Llama Rosa de la Adoración a través de cada célula de mi cuerpo, y expande la perfección hasta que esta llene todo mi ser y mi mundo. Flamea tu Llama de la Adoración a través de mis sentimientos para que expandan el Amor Divino en mí hasta que éste contagie a toda vida que yo contacte. Mantenme sellado en un pilar de Llama Rosa de Amor, Adoración, Confort y Perfección.',
        'El Gran Elohim ORIÓN, dice: “Te traigo la plenitud del Rayo y la Llama Rosa, como una alquimia espiritual disolvente para desterrar esos resentimientos y presiones de energía que están dentro de tu mundo emocional y profundamente sepultados dentro de tus memorias en tu cuerpo etérico. Esos recuerdos son causados por la infinidad de experiencias infelices que tuviste en el pasado, las cuales han formado heridas y cicatrices en tu cuerpo etérico. Estas cicatrices vuelven a abrirse ante la menor provocación, devolviendo hacia afuera nuevamente el veneno de enemistades, pleitos y malos entendidos del pasado. El hombre no sabe lo que lleva enterrado profundamente en ese reino que la ciencia llama subconsciente, donde yacen las memorias atrofiadas de cada una de las experiencias vividas en cada encarnación desde el primer día en que esa vida cayó de la ´Gracia` hasta el presente. El “Plan Divino” reúne a ciertas vidas, una y otra vez, presentándoles continuamente nuevas oportunidades para que enderecen las cosas entre ellas. En este mismo momento, si hay alguien en el mundo con quien tú no estás en completo acuerdo, trae la imagen de esa persona a tu mente y te daré la presión de mi sentimiento de perdón amoroso e incondicional hacia ese ser. Si lo aceptas, te verás libre del rechazo de energías que producen esos errores pasados”.',
        'En el Nombre de la Presencia de Dios que “YO SOY”, invoco a los Amados Pablo, Lady Rowena, Chamuel y Orión, y a todos los Grandes Seres y Poderes de la Luz que sirven en el Tercer Rayo y con la Llama Rosa del Amor Divino, para que ENCIENDAN (X3) la Llama del Amor y la Adoración como mil soles en cada parte de mi ser y mundo; en mis seres queridos y en cada persona, lugar y condición; en el Reino Elemental, las aves, los cuadrúpedos y toda cosa viviente en nuestra tierra, ahora mismo; y que la mantengan encendida allí hasta que toda vida aprisionada sea liberada por la Llama Rosa del Amor de Dios. ¡Les damos gracias!'],
      },
      Miércoles: {
        titulo: "MIÉRCOLES",
        subtitulo:
          "Cuarto Rayo Blanco de la Pureza, las Resurrección y la Ascensión.",
        texto: ['Amadísima Presencia de Dios “YO SOY” en mí y Amado Ser Crístico dentro de mi corazón: Te amo, te adoro. Tú conoces mi razón de ser. A través de las energías de mi mundo, hoy, haz que yo la cumpla; que no pierda una sola oportunidad, que jamás cometa un error de ninguna clase y, sobre todo, que no cometa errores de omisión.',
        'El Amado CLARIDAD, Elohim de la Pureza, dice: ´YO SOY` la Pureza que vive y respira en el centro electrónico de cada átomo que compone tu cuerpo físico. Yo estoy viviendo en cada célula de tu cuerpo, moviéndome alrededor del núcleo central de cada átomo de tu carne. Yo estoy contigo siempre. ´YO SOY` tu vida. ´YO SOY` la Luz Electrónica de la Pureza que vive y respira en tu cuerpo mental. ´YO SOY` la Luz viviente y respirante, la Llama de la Pureza y la Luz que invocas al gran océano de tu mundo emocional. ´YO SOY` la Luz Electrónica dentro de cada célula de tu vestidura etérica, en la cual has grabado esas células de impureza; y ahora Yo estoy expandiendo mi Pureza desde el centro de cada célula y átomo de tus cuatro cuerpos inferiores, EXPANDIENDO (X3) mi verdadera Naturaleza, que es la purificación de esta Tierra, todo lo que hay sobre ella, dentro de ella o en su atmósfera. Yo decreto que la Pureza en el centro de cada uno de tus electrones ahora se EXPANDIRÁ (X3), hasta que todo lo que manifiesta apariencia de limitación ya no pueda aprisionar tu vida en la discordia, y así las sombras dejarán de ser”.',
        'Amado Elohim de la Pureza: Te amo, te bendigo y te doy gracias por Tu gran servicio hacia mí y hacia toda la humanidad. Sella mi ser y el de todos mis hermanos en tu Óvalo de pura Luz Blanca incandescente, que desvía las corrientes de energía que reducen la frecuencia vibratoria de mis cuerpos inferiores. Yo decreto que la Pureza dentro de cada electrón en mi aura, mis sentimientos, mi mente, mis cuerpos etérico y físico ahora se EXPANDIRÁ (X3), y aquello que es limitación y sombra en mi mundo, no será más.',
        'El Amado GABRIEL, Arcángel de la Resurrección, dice: “La Religión no es cosa de ceremonia únicamente. Es asunto de la vida diaria y de cada hora que vivimos. Es cosa de sentido común, simple y ordinario. Es asunto de disciplina, dominio de sí mismo y contemplación. Es también el desarrollo del amor y la gratitud por la vida, por ese Dios que te ha dado la vida y ha sostenido tu Presencia en el Universo durante millones de años, esperando cumplir a través de ti  un destino que no puede ser cumplido por ningún otro individuo. Una sección del Gran Tapiz Cósmico que sólo tú puedes llenar”.',
        `Amado GABRIEL: Te amo, te bendigo y te doy gracias por lo que Tú significas para mí y para toda la humanidad. Carga estos, mis decretos, con Tu presión cósmica de Amor: 
        “YO SOY” La resurrección y la Vida de todo el Bien en mi corriente de vida. 
        “YO SOY” la Resurrección y la Vida de mi eterna juventud y belleza, de mi perfecta vista y oído, de mi fuerza, energía y salud ilimitada. 
        “YO SOY” la Resurrección y la Vida de mi provisión ilimitada de dinero y de toda cosa buena y perfecta. 
        “YO SOY” la Resurrección y la Vida de toda perfección en mi mundo y de mi Plan Divino cumplido ahora mismo.`,
        'El Amado Maestro Ascendido SERAPIS BEY, Chohán del Cuarto Rayo, dice: “Amados míos, la Llama de la Ascensión es Inteligente; Yo la he amado y he vivido con Ella por largo tiempo. Puede ascender cualquier condición en la que se encuentren. Puede ascender de la limitación a la armonía, de la aflicción a la paz, de la pobreza a la opulencia, de la discordia a la perfección. Es una de las actividades de la alquimia divina que el cuerpo estudiantil, en su mayoría, no ha pensado en utilizar. Si hay condiciones pesadas en sus mundos; si sus almas están decaídas, decaimientos que a veces no son suyos; si hay depresión en el grupo de personas que los rodean; si hay dificultades financieras de las cuales se enteran por las noticias: invoquen a nuestra Hermandad, que se encuentra en el Templo donde permanece encendida la Llama Blanca de la Ascensión, para que la envíen a sus vidas con la radiación que eleva al estado natural de armonía y felicidad. La Llama de la Ascensión y la Resurrección es un antídoto maravilloso contar toda depresión individual o colectiva”.',
        'Amado Maestro SERAPIS BEY: Te amo, te bendigo y te doy gracias por la Llama de la Ascensión, que es el retorno al hogar para mí y para toda la humanidad.',
        'En el Nombre de mi “Amada Presencia de Dios YO SOY” y la de toda la humanidad, te invoco, Amado Serapis Bey, y a todos los que integran Tu gloriosa Hermandad Blanca, para que mantengan encendida la Llama de la Ascensión, RESPLANDECIENDO (X3) a través de mis sentimientos, mi mente, mi cuerpo etérico, mi cuerpo físico, mi hogar, el hogar de mis seres queridos, mi negocio y todos mis asuntos. Que esa actividad estimuladora eleve todo mi mundo al Amor, Felicidad, Opulencia, Victoria y perfección de toda clase, eternamente sostenida. Llévenme a la victoria de mi Ascensión cuando mi servicio aquí en la Tierra esté cumplido. Mantengan la Llama de la Ascensión RESPLANDECIENDO (X3) a través de los asuntos mundiales, los negocios, las mentes, sentimientos y acciones de cada vida evolucionando en el planeta Tierra, para que lleguen más rápidamente a la Perfección. ¡Les doy las gracias!',
        ],
      },
      Jueves: {
          titulo: "JUEVES",
        subtitulo:
          "Quinto Rayo Verde de la Verdad, la Curación, la Consagración y la Concentración.",
        texto: ['Amada Presencia de Dios “YO SOY” en mí: Consagro vida este día al servicio de Dios, que es el Bien, para que sólo la Perfección tome cuerpo en mi cerebro. Que mis sentimientos se mantengan en calma, amorosos, bondadosos, felices y dispuestos a ayudar; que mis ojos no miren sino Perfección; que mis oídos no escuchen sino Perfección; que mis labios no hablen sino Perfección; que mis manos no hagan sino sanar y bendecir; que mis pies sean mensajeros del Bien; que mi cuerpo sea un instrumento fuerte y dispuesto a llevar la Perfección de Dios a todas partes.',
        'El Amado HILARIÓN, Chohán del Quinto Rayo, dice: “Si un individuo que está buscando Divinidad, Salud, Felicidad, pudiera comprender primero el poder de la atención sostenida, y luego, por su esfuerzo conciente, quitara su atención de los muchos imanes del mundo de las apariencias, anclándola en la Presencia de Dios, esa Presencia fluiría a través del él en la corriente que regresa, con la plenitud de todo lo que él pudiera desear. El Maestro Saint Germain ha repetido incesantemente: ´Donde está tu atención, allí estas tú. Aquello en lo que fijas tu atención, en eso te conviertes`. La radiación del Amor Divino y la Misericordia fluyen a través del Universo, pero el hombre está totalmente inconciente de ello. Este flujo del perdón de Dios afecta a justos e injustos por igual; pero la norma para el ser que desea avanzar en actuación conciente radica en el poder controlado de su atención”.',
        'Amado HILARIÓN: Te amo, te bendigo y te doy gracias por Tu ayuda a mí y a toda la humanidad. Cárgame con tu amor y comprensión de la exactitud de la Ley Cósmica, y con el servicio consagrado a Dios y al hombre. Cárgame con el ímpetu en la forma de presentar la Verdad a la humanidad, para que todo el que la oiga, la acepte. Gracias.',
        'El Amado RAFAEL, Arcángel de la Consagración, dice: “Conságrate diariamente. Si tus ojos ven iniquidad, tu sabes donde está el “YO SOY”. Di mentalmente: ´Padre perdona mi transgresión a la Ley de Amor. Amado Rafael, consagra mis ojos para que vean únicamente Perfección`. Si escuchas chismes y murmuraciones; si tus manos hacen gestos impacientes y dejas brotar la ira; si tus labios pronuncian palabras duras, di: ´Padre, perdóname por el mal uso de tu energía`. ¿Qué importa que tengas que repetirlo? Paderewski no llegó a ser un gran pianista en un sólo día. Las únicas corrientes de vida que están en peligro son aquellas que no tienen deseos de levantarse y volver a intentarlo. Yo reconsagraré a cualquiera de tus vehículos veinticuatro veces cada hora, si lo necesitas y me lo pides. No me importa. ¡Esa es mi razón de ser!',
        'Amado RAFAEL: Te amo, te bendigo y te doy gracias por todo lo que has hecho por mí y por toda la humanidad. Séllanos en Tu Llama de la Consagración y la Perfección, y ayúdame a estar conciente únicamente de la Perfección. Yo Pienso Perfección, Siento Perfección, Veo Perfección, Oigo Perfección, Hablo Perfección. “YO SOY” y manifiesto solamente Perfección este día.',
        'El Amado VISTA (CICLOPEA), Elohim de la Concentración, la Música y el “Ojo Todo Avizor” de Dios, dice: “¿Qué puedes efectuar, aún en las actividades mundanas de tu diario vivir, si no tienes concentración? Sin ella sólo hay mediocridad. Apenas se rasguña, como quien dice, la superficie. “Aquellos que resuelven elevarse por encima de las masas, toman una faceta de la vida y la desarrollan con maestría, decidiendo dentro de ellos mismos llegar a la excelencia, por lo menos en esa línea de expresión. Su desarrollo, lo mismo que su eficacia, va de acuerdo con la concentración de esas energías. “La Ley dice que lo que tú comienzas lo puedes cumplir cuando eso está de acuerdo con el Plan Divino de Perfección, bien sea la curación, precipitación, libertad económica, juventud eterna o la restauración de un órgano físico; no importa lo que sea, es posible, pero la constancia de mi Rayo es necesaria para lograrlo”.',
        'Amado Elohim VISTA: Te amo, te bendigo y te doy las gracias por Tu gran servicio a nuestra Tierra. Cárgame con Tu Poder de Concentración, para convertirme en Maestro aquí y ahora. Gracias.'],
      },
      Viernes: {
          titulo: "VIERNES",
        subtitulo:
          "Sexto Rayo Oro-Rubí de la Paz, la Curación, la Gracia y la Ministración.",
        texto: ['Amada Presencia de Dios “YO SOY” en mi: Te amo, te adoro. Derrama en mi, este día, Tu Llama Oro-Rubí para bendecir cada célula de mi cuerpo físico y todos los poderes de la naturaleza que me sirven tan bien- Que todo aquel que toque “el borde de mi manto” sienta Tu Amor, Tu Paz y Tu Perfección, porque “YO SOY” la Presencia de la Bendición, y bendigo todo y a todos los que contacte este día.',
        'El Amado Maestro JESÚS, anterior Chohán del Sexto Rayo, dice: “Las demandas de tiempo, energía, atención y servicio de todo el que está comprometido en algún esfuerzo espiritual constituyen un gran obstáculo para su progreso individual, a menos que aprenda a aquietar conscientemente las energías de su propio mundo para que nueva fuerza, fe y poder puedan ser suplidos por su Presencia “YO SOY” y por los Seres Divinos que lo están asistiendo. “Yo se de esto por mi propia experiencia. Durante mi Ministerio, como hoy en día, el mundo y su gente requieren mucha asistencia, y hay una gran tendencia a precipitarse a servir, sin darse antes el tiempo necesario para recuperarse en la “Fuente Cósmica”. Refiriéndome a mi propia experiencia, recordarán que a menudo me ausentaba e iba a las montañas a orar. Ningún estudiante puede servir con eficacia si no comprende la necesidad de tomar un tiempo –sin separarse del mundo- para entrar en el Silencio y extraer la fuerza y la santidad necesarias desde la FUENTE DE TODO BIEN. Luego, éstas pueden ser dispersadas con calma y dignidad, auxiliando amorosamente al prójimo”.',
        'Amado Maestro JESÚS: Te amo, te bendigo y te agradezco por todo lo que significas para mi y para toda la humanidad. Cárgame con la Conciencia y Amor del JESUCRISTO Ascendido, y con la Luz que me guíe para seguir tu incomparable ejemplo.',
        'La Amada Maestra Ascendida LADY NADA, anterior Chohán del Sexto Rayo, dice: “Hoy ustedes también están sembrando profundamente sus raíces en la Llama del corazón, de donde viene el aliento, el propio latido de vida del cuerpo, de donde sale la curación de la carne, de donde viene el suministro de vuestras mesas y hasta el techo que cubre vuestras cabezas. Así como vuestras raíces están ancladas en Dios buscando el alimento espiritual, así vuestro florecimiento será manifestado ante todos los hombres. Aquello que el hombre hace en secreto se manifiesta para que todos lo vean. La humanidad va a venir hacia ti, toda confusa y esperando en ti. Acuérdate de mí, Nada, y libéralos con amor”.',
        'Amada LADY NADA: Te amo, te bendigo y te agradezco el amor que fluye de ti hacia mi y hacia toda la humanidad. Mantenme sellado en el Poder de tu Llama Rubí que sana, bendice y libera todo lo que yo contacte.',
        'JUAN EL AMADO, Chohán del Sexto Rayo, dice: “Cuando sirven con la Gran Hermandad Blanca, ustedes se inician entrenando sus propios cuatro vehículos inferiores. Ustedes son los conductores de las energías de Amor y Luz, y naturalmente, sus cuatro vehículos tienen que ser una semblanza de orden para que puedan ayudar a alguien más. Pero cuando reciban tal orden y soliciten que sea sostenido mediante la Gracia, recuerden que hay diez mil millones de almas que estarán caminando detrás de ustedes. Así que, en su deseo de servir a la vida, no dejen una trampa oculta de la cual sean conocedores y dentro de la que ellos, inconscientemente, puedan caer; es decir, una mala interpretación de una palabra, una sentencia que pueda ser utilizada como “libertinaje” en vez de “liberación”; porque éste es un Pacto hecho entre el Cielo y la Tierra, por ustedes y su Creador”.',
        'Amado JUAN, El Discípulo Amado: Te amo, te bendigo y te doy gracias por Tu gran servicio a la Tierra. Mantennos sellados en el Poder del Sexto Rayo, que sana, ama y bendice la liberación de toda Vida.',
        'El Amado URIEL, Arcángel de la Provisión, dice: “El Ángel del Suministro tiene la voluntad de ocuparse de una sola corriente de vida. Para cada ser humano, para cada haragán rezagado de otro sistema y para cada espíritu guardián aprisionado aquí, hay un Ángel Suministrador que voluntariamente cumple la función de proteger esa corriente de vida por tanto tiempo como ella elija permanecer en la Tierra o formar parte de su evolución. A dicho ser se le llama a menudo “Ángel Guardián”. ¿Cómo te gustaría trabajar con una misma persona durante incontables millones de años? Tu Ángel Guardián ni siquiera asiste a un Retiro, cuando está en actividad si “su” corriente de vida no asiste también. ¡Piensa en eso! Es un caso de Prisión por Amor que no tiene paralelo. El Ángel Suministrador está obligado por Ley a no separarse de su pupilo y mandarle un rayo de luz a la conciencia, en cada oportunidad, con la esperanza de que busquen un poco más alto”.',
        'Amado URIEL: Te amo, te bendigo y te doy gracias a Ti y a mi Ángel Suministrador por vuestro abnegado servicio hacia a mi durante tantos eones. Ayúdanos a mi y a mi Ángel a mantenernos sin desvío en el sendero de la pureza, la armonía y la felicidad.',
        'El amado TRANQUILIDAD, Gran Elohim de la Paz, dice: “”YO SOY” el Elohim de la Provisión y la Paz. Ustedes, que han dado su interés y su vida a las actividades del Séptimo Rayo, representado por el Amado Maestro Saint Germain, están emergiendo lentamente del lodo de la creación y la limitación humana. Nosotros estamos tratando de fundar una gran base para este movimiento mundial, tratando de hacer de cada uno de ustedes un Pilar de Fuego Violeta. Pero les puedo decir aquí y ahora, que a menos que se conserven en paz, ininterrumpidamente, como individuos y como unidad colectiva, no importa cuán perfectamente construyan, al final no tendrán mas que cenizas si todavía sostienen en la conciencia la radiación desintegradora de los “siete pecados capitales” (lujuria, ira, malicia, odio, temor, gula, glotonería, pereza, envidia, orgullo y arrogancia) y sus demás ramificaciones. La paz no es una cualidad negativa. Es eminentemente positiva y una concentración de poder. ¿Cuánto control se necesita para mantenerse en paz? Consérvense absolutamente en calma y dueños de toda situación, a pesar de cualquier provocación en el seno de sus familias, entre sus compañeros de trabajo o en el mundo en general”.',
        'Amada Presencia de Dios “YO SOY” en mí y en toda la humanidad; Amados Jesús, Juan, Nada, Uriel, mi propio Ángel Guardián y Gran Elohim de la Paz: Los amo, los bendigo y les doy gracias en nombre de toda la humanidad por vuestro servicio a nuestra Tierra durante tanto tiempo. ENCIENDAN (X3) sus Llamas Cósmicas de Amor, Gracia, Provisión, Curación y Paz en mí, para que irradien a través de mi, bendiciendo y ayudando a armonizar a toda vida que yo contacte. Gran Elohim de la Paz: Envuelve todos mis esfuerzos constructivos en tu Gran Llama de Amor y Paz. Flamea tu Llama de Paz, como mil soles en mi cerebro y mis sentimientos, en los de toda cosa viviente en el Universo y en todos los que vendrán aquí en el futuro. Mantenla encendida hasta que la Paz en la Tierra y la Buena Voluntad sean una realidad para siempre sostenida y expandiéndose eternamente. ¡Te damos gracias!'],
      },
      Sábado: {
          titulo: "SÁBADO",
        subtitulo:
          "Séptimo Rayo Violeta de la Misericordia, la Compasión, la Invocación, la Transmutación y la Liberación.",
        texto: ['Amada Presencia de Dios “YO SOY” en mí: Hoy estoy vivo, con esa vida majestuosa que me da el Padre. Por la vida que utilicé mal ayer, invoco la Ley del Perdón y acepto la poderosa actividad de la Llama Violeta Transmutadota, ya que hoy, dentro de mi “Círculo Mágico de Luz” –mi anillo de fuego impenetrable- poseo los dones de la vida divina, inmaculados, puros, limpios. Hoy puedo convertirme en lo que Dios tiene dispuesto: mi Ser Crístico en acción, pues “YO SOY” LA CONCIENCIA CRÍSTICA (X3) ahora manifestada y eternamente sostenida. Mantenme sellado en un Pilar de Fuego Violeta que trascienda toda creación humana en, a través, alrededor de mí, o aquello que se está devolviendo en busca de redención, hasta que yo está totalmente libre y ascendido.',
        'El Amado Maestro SAINT GERMAIN, anterior Chohán del Séptimo Rayo, actual Rey de la Edad Dorada y Avatar Acuarios, encargado de la Tierra y sus evoluciones en los próximos dos mil años, dice: “Tomen su tiempo para santificarse. Yo les pido que aprendan a aquietarse, aún cuando no haya ninguna emergencia. Practiquen aquietar su pensamiento, no lo dejen correr; hagan que sus memorias etéricas no resuciten nada discordante; detengan la inquietud de sus cuerpos físicos; y luego, si pueden, vuélvanse suavemente hacia el Ser Supremo –o hacia un solo Ser de Luz- hasta que se sientan anclados en la Paz. ¡Con una persona que logre hacer esto, se puede salvar una ciudad! Yo he resuelto que la ciencia y el uso del Fuego Violeta sea establecido en un ser no ascendido, como una manifestación científica absolutamente irrefutable, que no se pueda negar. Yo estoy más ansioso de lo que ustedes puedan estar jamás, por que aprendan a usar la Llama Violeta, ya que ustedes tienen que hacer mis veces en el mundo de las formas, puesto que Yo, por Ley Cósmica, debo permanecer detrás del vello. Ustedes que son mis amigos, acéptenme. Permítanme caminar por la Tierra a través de ustedes. Dejen que Yo los ayude con esta Alquimia Divina. Vengan a los Templos del Fuego Violeta mientras duermen por las noches, y Yo me sentaré a explicarles, una y otra vez, lo que es la ciencia y la alquimia de la Llama Violeta. Sapan que hay un sitio reservado para ustedes en el hogar y en el corazón de Saint Germain”.',
        'La Amada Madre MERECEDES, Chohán del Séptimo Rayo, dice: “Los elevaré sobre las alas de un Águila y se REMONTARAN COMO UNA PALOMA. Hollen suavemente y con reverencia la faz de la Tierra, recordando que la vida elemental ha creado esta plataforma para que ustedes caminen sobre ella. Cuando invoquen la Ley del Perdón por sus transgresiones a la Ley Espiritual, recuerden a su compañero de viaje que no sabe lo que ha hecho y necesita rectificación. Un verdadero chela se da cuenta de lo que él hace, piensa o siente, proyecta un patrón en el mundo de la forma. Proyecten patrones de armonía, patrones de vida familiar ejemplar, porque lo que afecta a uno, finalmente afectará a TODO; en la Unidad de Propósito, esta querida Tierra se convertirá en un Planeta de Perfección y ocupará el lugar que le corresponde en esta Galaxia. Como saben, mis amados, cada aliento y palabra que pasa por sus labios es un ser viviente; ojalá que estos pequeños sean siempre vestidos con ropajes de Luz, y lleven el mensaje que su Santo Cristo Interno desea darle a la humanidad, una bendición para sus hermanos y hermanas. Cuando ofrezcan su Grial a alguien, estén seguros que la esencia que le dan a su compañero de viaje es algo que él está buscando. Conocer ´El Lugar Secreto que es la Morada del Más Alto Dios Viviente` en el corazón, es uno de los pasos más importantes en el proceso de la manifestación. El chela debe estar al mando de su mundos de pensamiento y sentimiento, manteniéndolos positivos. Si el control no es mantenido cuidadosamente, en vez de bendecir a toda vida, darán poder a las vibraciones negativas en ustedes mismos y en aquellos que están a su alrededor. Les aconsejo, les imploro…insistan en el desarrollo de la maestría sobre sus mundos de pensamiento y sentimiento; de esa manera, podrán ayudar a nuestro Amado Maestro Saint Germain a manifestar la nueva Era de la Liberación Espiritual para toda vida. ´¡Que haya PAZ en la Tierra y que comience por mí!`. A medida que se desarrollen con más fuerza en su maestría personal, los sostendré en la Palma de Mi Mano”.',
        'El Amado ZADQUIEL, Arcángel de la Invocación y la Transmutación, dice: “¿Saben que la vida contenida en una palabra desagradable viene a ustedes para que la rediman y la liberen? La vida contenida en una mirada dura o en un gesto airado viene a ustedes, sacerdotes o sacerdotisas de la Orden de ZADQUIEL, para que la liberen con amor. No personalicemos la energía. No reciban con rebelión, ni sientan que es injusto aquello que vienen a ustedes en sus pensamientos y experiencia diaria. Viene porque hay focos en esta octava no ascendida que deben redimir, purificar y liberar. Allí donde existe un foco del Fuego Sagrado, donde quiera que haya una vida que posee el conocimiento de la Llama Violeta, esa energía tiene la posibilidad de ser redimida y devuelta a la Primera Causa Universal. ¡Oh, qué dicha poder moverse en el Universo liberando energías, amándolas hasta redimirlas, y permaneciendo sereno en la Maestría de la propia Divinidad! Las palabras dichas en broma, acerca de otra vida, que no son habladas para bendecir, son una maldición. ¡Yo pido que toda vida sea liberada de los inconvenientes de semejantes errores!”.',
        'El Amado ARCTURUS, Elohim de la Invocación, el Ritmo y la Liberación, dice: “YO SOY el Elohim de la Invocación y el Ritmo, que te trae a ti y a toda vida, Libertad Infinita a través del uso del Fuego Violeta, cuando la deseas lo suficiente. ´YO SOY` aquel que responde a la llamada del corazón de cada individuo que desea sinceramente ser libre de la enfermedad, la carencia, el temor y la limitación de toda clase  y descripción. Dentro de esa vida misma está la plenitud de Dios. Hoy te insto, con toda la intensidad y presión de mi Ser, a que desarrolles tu vida; desarrolla las cualidades de perfección que hay en ella. Invoca lo que desees del corazón de la vida que fluye de lo Universal, y llámame si deseas liberar a la manifestación exterior –desde el centro de tu propia vida- todo poder, cualidad, don y actividad que sea requerido para perfeccionar tu mundo individual y el de tu hermano humano. Donde quiera que haya una vida que desee sinceramente la liberación, y que la pida y la decrete con ritmo constante, allí estaré Yo para darle mi asistencia, hasta que la liberación se manifieste físicamente”.',
        'Amado Maestro SAINT GERMAIN, Amado ZADQUIEL, Amado ARCTURUS, Amada Madre MERCEDES –actual Chohán del Séptimo Rayo- y todos los que desempeñan un servicio ene. Séptimo Rayo, los amo, los bendigo y les doy gracias por su gran servicio a mí y a toda la humanidad. En el Nombre de la Presencia de Dios “YO SOY”, y por el poder magnético del Fuego Sagrado investido en mí como Sacerdote (o Sacerdotisa) de la Orden de ZADQUIEL, hago esta Invocación: ÁNGELES DEL FUEGO VIOLETA (X3)¡VENGAN! (X3) Y mantengan el Amor del Fuego Liberador RESPLANDECIENDO (X3) a través de mi aura y mis sentimientos, mi cerebro y mi mundo mental, mi cuerpo etérico, cada célula de mi cuerpo físico, mi hogar, mis negocios, mis finanzas y asuntos, y háganlo por toda vida sobre el planeta Tierra hasta que toda creación humana, su causa y núcleo, sean disueltos y transmutados en Pureza y Perfección, y nuestra Tierra sea verdaderamente la SANTA ESTRELLA DE LALIBERTAD. Les agradezco por la respuesta a esta llamada de mi corazón, pues EL FUEGO VIOLETA DEL AMOR LIBERADOR NUNCA FALLA (X3) en producir Pureza y Perfección, y “YO SOY” ese FUEGO VIOLETA.',
        'Amado Maestro SAINT GERMAIN y Amada Diosa de la OPORTUNIDAD: Les comprometo mi Luz, mi vida y mi amor, procurando liberar los ímpetus de Perfección que haya en mi vida, para ayudar a traer Liberación a cada parte de vida sobre nuestro amado planeta Tierra tan pronto como sea posible. ¡Así sea!'],
      },
      Domingo: {
          titulo: "DOMINGO",
        subtitulo:
          "Primer Rayo Azul Cristal de la Fuerza, el Poder y la Voluntad de Dios.",
        texto: ['AMADA PRESENCIA DE DIOS “YO SOY” DENTRO DE MI CORAZÓN , TE AMO , TE ADORO Y TE INVOCO PARA QUE ENCIENDAS EN MI LA LLAMA CRISTAL Y AZUL Y QUE LA VOLUNTAD DE DIOS SE MANIFIESTE EN TODO LO QUE YO HAGA HOY. ME DOY CUENTA DE QUE DENTRO DEL LATIDO DE MI CORAZÓN ESTÁ EL PLAN DIVINO DE DIOS PARA MÍ, COMO TAMBIÉN LA MANERA DE TRAERLO A LA MANIFESTACIÓN. ENTRO EN EL SILENCIO. ESCUCHO Y SÉ LO QUE TENGO QUE HACER. MIENTRAS MANTENGO LA ATENCIÓN EN EL PLAN DIVINO. SE HACE EN LA FORMA.',
        'YO SOY LA FÉ EN EL PODER DE DIOS EN MÍ PARA DIRIGIRME, PROTEGERME, ILUMINARME, SANARME, PROVEERME , SOSTENERME Y DARME LO QUE SEA NECESARIO-',
        'EL ASCENDIDO MAESTRO MORYA GRAN DIRECTOR DEL PRIMER RAYO DICE ASÍ: MIDE BIEN LA VISIÓN QUE TE VENGA DE CUALQUIERA PARTE DE LA VIDA, AQUELLO QUE ELEVE, AQUELLO QUE UNIFIQUE, AQUELLO QUE LIBERTA, AQUELLO QUE VUELVA LA CONCIENCIA HACIA DIOS, ¡ESA ES LA VOLUNTAD DE DIOS! NO NECESITA NI MEDIDA OCULTA NI CONSEJERO EXTERIOR. LA VIDA QUE LATE DENTRO DE TU CORAZÓN SABE LO QUE ES CONSTRUCTIVO, LO QUE ALIVIA Y LO QUE LIBERTA DE LA ESCLAVITUD. ¡ESO ES DE DIOS!',
        'AMADO MORYA, TE AMO, TE BENDIGO Y TE DOY LAS GRACIAS POR TU SERVICIO HACIA MÍ Y HACIA TODA LA HUMANIDAD, ENVUÉLVEME EN TU LLAMA AZUL DE AMOR Y HAZ QUE YO SIENTA TU FUERZA Y PODER, ASÍ COMO QUE RECIBA YO LAS IDEAS DE DIOS Y LAS TRAIGA LA MANIFESTACIÓN EXTERIOR PARA BENDECIR A MIS HERMANOS HUMANOS. AYÚDAME A BENDECIR A MI PRESENCIA DIVINA “HÁGASE TU VOLUNTAD Y NO LA MÍA” AYÚDAME A SENTIR Y COMPRENDER TU OBEDIENCIA ILUMINADA A ESA VOLUNTAD; TU HUMILDAD ESPIRITUAL ANTE EL AMOR DE DIOS, Y TU RESPETO POR DIOS, POR SUS REPRESENTANTES Y POR LA PRESENCIA DE DIOS EN CADA CORAZÓN HUMANO.',
        'EL GRAN ARCÁNGEL MIGUEL, DE LA PROTECCIÓN Y DEFENSOR DE LA FE DICE ASÍ: A TRAVÉS DE LA LUZ DE MÍ CORAZÓN Y DEL TUYO CREAMOS PARA TI AHORA Y EN ESTE MUNDO DE APARIENCIA UN SENDERO DE AMOR, PAZ, CONSUELO, OPULENCIA, ILUMINACIÓN Y BIENESTAR FÍSICO, MENTAL, EMOCIONAL Y ESPIRITUAL. SENTIRÁS LA LUZ DE TU CORAZÓN CREANDO ESTE SENDERO FRENTE A TÍ CUANDO SALGAS DE TU HABITACIÓN CADA MAÑANA. CAMINA EN EL SENDERO DE LOS ÁNGELES TODO EL DÍA, CON LA MISMA SEGURIDAD QUE SI PASARAS A TRAVÉS DE UNO DE LOS RAYOS QUE HAN SIDO ESTABLECIDOS COMO SENDEROS PERMANENTES EN LA SUSTANCIA DE LA TIERRA, POR LOS MAESTROS.',
        'AMADO MIGUEL, TE AMO, TE BENDIGO Y TE DOY GRACIAS POR TU GRAN SERVICIO HACIA MÍ Y TODA LA HUMANIDAD EN TANTOS SIGLOS. ENVÍA TUS ÁNGELES DE PROTECCIÓN A ENVOLVERME Y A MIS SERES QUERIDOS, ASÍ COMO A TODOS LOS SERES CONSTRUCTIVOS SOBRE LA TIERRA, CORTA Y LIBERTANOS DE LOS PENSAMIENTOS Y SENTIMIENTOS QUE NO SE AJUSTAN AL CONCEPTO INMACULADO DE DIOS PARA NOSOTROS. TE DOY GRACIAS.',
        'EL GRAN ELOHIN HÉRCULES DICE ASÍ: “¿ESTAS SATISFECHO CON LO QUE TÚ ERES HOY? ¿ESTÁS CONTENTO CON MEDIO PAN CUANDO PODRÍAS TENER UNO COMPLETO? ¿ESTÁS RESIGNADO A VIVIR EN LA LIMITACIÓN Y EN CUERPO QUE SE CORROMPE? PORQUE ES LO QUE TU DESEES, LO QUE SE MANIFIESTA. ¡OH, AMADO ESTUDIANTE DE LA LUZ! SOBRE TU FRENTE FLAMEA LA LLAMA DE HÉRCULES. CADA MAÑANA ACUÉRDATE DE RECONOCERLA ANTES DE PROCEDER A LAS ACTIVIDADES DEL MUNDO EXTERIOR Y EXPRESAR EL PROPÓSITO DE CONVERTIRSE EN AQUELLO QUE ES LA VOLUNTAD DE DIOS. ACUÉRDATE DE HÉRCULES A MEDIDA QUE AVANZAS. NO ACEPTES LIMITACIONES EN TI CUANDO TÚ SABES QUE SOLO REQUIERE EL EJERCICIO DE TU VOLUNTAD PARA EXTRAER DE ADENTRO DE TI TODO LO QUE REQUIERAS.',
        'AMADO HÉRCULES, TE AMO TE BENDIGO Y TE DOY GRACIAS POR TU GRAN SERVICIO A TODA NUESTRA TIERRA Y TODO LO QUE EN ELLA HAY. CARGA CADA UNO DE MIS CUERPOS –FÍSICO, ETERICO, MENTAL Y EMOCIONAL- , CON LA FUERZA DE HÉRCULES Y EL PODER DE TU AMOR EL CUAL DA PROTECCIÓN INVENCIBLE EN TODO MOMENTO.',
        'EN EL NOMBRE DE LA PRESENCIA DE DIOS “YO SOY”, EN EL NOMBRE DE HÉRCULES, EXPRESO MI VOLUNTAD DE SER DIVINAMENTE LIBRE, EN MENTE, SENTIMIENTOS, CUERPO, FINANZAS, MUNDO Y ASUNTOS. EXPRESO MI VOLUNTAD DE SER MAESTRO DIVINO, DE SER EL DIOS ENCARNADO QUE PROMETIÓ JESÚS.'],
      }
    };
  },
  computed: {
    dia() {
      const diaSeleccionado = this.$route.params.id;
      return this[diaSeleccionado];
    },
  },
};
</script>